// <auto-generated />
using System;
using DatingApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatingApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("DatingApp.Core.Aggregates.Profiles.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LookingFor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("DatingApp.Core.Aggregates.Profiles.Entities.Profile", b =>
                {
                    b.OwnsOne("DatingApp.Core.Aggregates.Profiles.ValueObjects.Birthday", "Birthday", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Day")
                                .HasMaxLength(2)
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Month")
                                .HasMaxLength(2)
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Year")
                                .HasMaxLength(4)
                                .HasColumnType("INTEGER");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("Birthday")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
